### ISSUE TITLE
bot: create a new instance from the dashboard using templates

### ISSUE THREAD

**Issue by mfreeman451** [carverauto/threadr#105]
Use k8s to automatically deploy new pod:

- [ ] Bot deployment template
- [ ] Automate deployment
- [ ] Apply deployment

## Template the bot deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .BotName }}-bot-deployment
  labels:
    app: {{ .BotName }}-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .BotName }}-bot
  template:
    metadata:
      labels:
        app: {{ .BotName }}-bot
    spec:
      containers:
      - name: {{ .BotName }}-bot
        image: your-bot-image:latest
        env:
        - name: BOT_TOKEN
          value: {{ .BotToken }}
        - name: CHANNEL_ID
          value: {{ .ChannelId }}
```

## Automate the deployment process

```go
func createBotInstance(customerId, botName, botToken, channelId string) error {
    // Load the deployment template
    deploymentYAML := loadDeploymentTemplate("bot-deployment-template.yaml")

    // Replace placeholders with actual values
    deploymentYAML = strings.ReplaceAll(deploymentYAML, "{{ .BotName }}", botName)
    deploymentYAML = strings.ReplaceAll(deploymentYAML, "{{ .BotToken }}", botToken)
    deploymentYAML = strings.ReplaceAll(deploymentYAML, "{{ .ChannelId }}", channelId)

    // Use Kubernetes API or CLI to apply the deployment
    return applyKubernetesDeployment(deploymentYAML)
}
```

## Apply the deployment

```go
import "k8s.io/client-go/kubernetes"
import "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
import "k8s.io/apimachinery/pkg/util/yaml"

// applyKubernetesDeployment applies the deployment to the Kubernetes cluster
func applyKubernetesDeployment(deploymentYAML string) error {
    clientset, err := kubernetes.NewForConfig(config)
    if err != nil {
        return err
    }

    // Decode YAML to JSON
    dec := yaml.NewYAMLOrJSONDecoder(strings.NewReader(deploymentYAML), 1024)
    var deploymentSpec unstructured.Unstructured
    if err := dec.Decode(&deploymentSpec); err != nil {
        return err
    }

    // Apply the deployment
    _, err = clientset.AppsV1().Deployments("your-namespace").Create(context.TODO(), &deploymentSpec, v1.CreateOptions{})
    return err
}
```
