### ISSUE TITLE
azure: add vllm to AKS

### ISSUE THREAD

**Issue by mfreeman451** [carverauto/threadr#71]
Requirements:

- [x] #72
- [ ] #78
- [ ] #73
- [ ] #76
- [ ] #77
- [ ] Apply YAML

```yaml
kubectl apply -n kserve-test -f - <<EOF
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama-2-7b
spec:
  predictor:
    containers:
    - args:
        - --port
        - "8080"
        - --model
        - /mnt/models
      command:
        - python3
        - -m
        - vllm.entrypoints.api_server
      env:
        - name: STORAGE_URI
          value: gs://kfserving-examples/llm/huggingface/llama
      image: kserve/vllmserver:latest
      name: kserve-container
      resources:
        limits:
          cpu: "4"
          memory: 50Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 50Gi
          nvidia.com/gpu: "1"
```
